# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-25 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator_id', models.IntegerField(verbose_name='账户_id')),
                ('administrator_name', models.CharField(default='root', max_length=30, verbose_name='用户昵称')),
                ('administrator_pwd', models.CharField(max_length=100, verbose_name='用户密码')),
                ('administrator_jifen', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='积分')),
            ],
            options={
                'verbose_name': '管理员信息',
                'verbose_name_plural': '管理员信息',
                'db_table': 'super_user',
            },
        ),
        migrations.CreateModel(
            name='Buy_peoples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_people_name', models.CharField(max_length=50, verbose_name='购买人姓名')),
                ('buy_people_alljifen', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总积分')),
                ('buy_people_keyongjifen', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='可用积分')),
                ('buy_people_allmoney', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总消费金额 ')),
                ('buy_people_phone', models.CharField(default='18888888888', max_length=11, verbose_name='购买人手机号')),
                ('buy_people_addr', models.TextField(default='暂无', verbose_name='购买人地址')),
                ('buy_people_age', models.CharField(choices=[('a', '<19'), ('b', '20-35'), ('c', '36-55'), ('d', '>55'), ('e', '不确定')], default=2, max_length=20, verbose_name='购买人年龄')),
                ('buy_people_sex', models.CharField(choices=[('a', '男'), ('b', '女')], default=1, max_length=20, verbose_name='购买人性别')),
                ('buy_people_is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('administrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInfo.Administrators', verbose_name='管理员账户_id')),
            ],
            options={
                'verbose_name': '购买人信息',
                'verbose_name_plural': '购买人信息',
                'db_table': 'buy_peoples',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(max_length=50, verbose_name='商品编号')),
                ('goods_name', models.CharField(default='无名氏', max_length=50, verbose_name='商品名称')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('goods_kucun', models.IntegerField(default=0, verbose_name='库存')),
                ('goods_xiaoliang', models.IntegerField(default=0, verbose_name='销量')),
                ('goods_text', models.TextField(default='暂无描述', verbose_name='商品描述')),
                ('goods_guige', models.CharField(default='无', max_length=100, verbose_name='商品规格')),
                ('administrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInfo.Administrators', verbose_name='管理员账户_id')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Goods_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leibie_id', models.CharField(default='LB0001', max_length=20, verbose_name='类别编码')),
                ('leixing', models.CharField(max_length=50, verbose_name='类别名称')),
                ('jibie', models.CharField(default='一级', max_length=15, verbose_name='级别')),
                ('administrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInfo.Administrators', verbose_name='管理员账户_id')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
                'db_table': 'goods_types',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='20190125120541268492', max_length=50, verbose_name='订单编号')),
                ('dingdanshijian', models.DateTimeField(auto_now=True, verbose_name='订单时间')),
                ('chengjiao_price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='成交单价')),
                ('chengjiao_allmoney', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='成交总金额')),
                ('youhuijine', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='优惠金额')),
                ('goumailiang', models.IntegerField(default=0, verbose_name='购买量')),
                ('huodejifen', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='获得积分')),
                ('zhifufangshi', models.CharField(choices=[('a', '现金'), ('b', '刷卡'), ('c', '支付宝'), ('d', '微信')], default=2, max_length=20, verbose_name='支付方式')),
                ('order_is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('administrator_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userInfo.Administrators', verbose_name='管理员账户_id')),
                ('buy_prople', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInfo.Buy_peoples', verbose_name='购买人')),
                ('goods', models.ManyToManyField(default=1, to='userInfo.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInfo.Goods_types', verbose_name='商品类别'),
        ),
    ]
