# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-27 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInfo.Goods', verbose_name='商品信息')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='dingdanshijian',
            field=models.DateTimeField(auto_now_add=True, verbose_name='订单时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='20190127194832052904', max_length=50, verbose_name='订单编号'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInfo.Order', verbose_name='订单信息'),
        ),
    ]
