# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-27 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0002_auto_20190127_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='20190127195336640031', max_length=50, verbose_name='订单编号'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
