# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-27 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0003_auto_20190127_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='administrators_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userInfo.Administrators', verbose_name='管理员信息'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='20190127205605707565', max_length=50, verbose_name='订单编号'),
        ),
    ]
