# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-27 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0004_auto_20190127_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='administrators_id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.IntegerField(verbose_name='购买数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='20190127205744886455', max_length=50, verbose_name='订单编号'),
        ),
    ]
