# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-28 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0005_auto_20190127_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='goods',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='20190128091823982164', max_length=50, verbose_name='订单编号'),
        ),
    ]
