# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-28 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0006_auto_20190128_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='chengjiao_price',
        ),
        migrations.AddField(
            model_name='order',
            name='chengjiao_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='优惠前金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='chengjiao_allmoney',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='优惠后金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='20190128162253677391', max_length=50, verbose_name='订单编号'),
        ),
    ]
