# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-30 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0008_auto_20190129_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='xiaohaojifen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='消耗积分'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='20190130103631559078', max_length=50, verbose_name='订单编号'),
        ),
    ]
