# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-30 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0009_auto_20190130_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='20190130114100582710', max_length=50, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zhifufangshi',
            field=models.CharField(choices=[('a', '现金'), ('b', '刷卡'), ('c', '支付宝'), ('d', '微信'), ('e', '积分兑换')], default=2, max_length=20, verbose_name='支付方式'),
        ),
    ]
